/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CiclosDataInicioRouteImport } from './routes/ciclos/$dataInicio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CiclosDataInicioRoute = CiclosDataInicioRouteImport.update({
  id: '/ciclos/$dataInicio',
  path: '/ciclos/$dataInicio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ciclos/$dataInicio': typeof CiclosDataInicioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ciclos/$dataInicio': typeof CiclosDataInicioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ciclos/$dataInicio': typeof CiclosDataInicioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ciclos/$dataInicio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ciclos/$dataInicio'
  id: '__root__' | '/' | '/ciclos/$dataInicio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CiclosDataInicioRoute: typeof CiclosDataInicioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciclos/$dataInicio': {
      id: '/ciclos/$dataInicio'
      path: '/ciclos/$dataInicio'
      fullPath: '/ciclos/$dataInicio'
      preLoaderRoute: typeof CiclosDataInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CiclosDataInicioRoute: CiclosDataInicioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
