/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PessoasAdicionarNoCicloAtualRouteImport } from './routes/pessoas.adicionarNoCicloAtual'
import { Route as CiclosDataInicioRouteImport } from './routes/ciclos.$dataInicio'
import { Route as PessoasNomePessoaRendimentosNomeRouteImport } from './routes/pessoas.$nomePessoa.rendimentos.$nome'
import { Route as PessoasNomeRendimentosAdicionarNoCicloAtualRouteImport } from './routes/pessoas.$nome.rendimentos.adicionarNoCicloAtual'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasAdicionarNoCicloAtualRoute =
  PessoasAdicionarNoCicloAtualRouteImport.update({
    id: '/pessoas/adicionarNoCicloAtual',
    path: '/pessoas/adicionarNoCicloAtual',
    getParentRoute: () => rootRouteImport,
  } as any)
const CiclosDataInicioRoute = CiclosDataInicioRouteImport.update({
  id: '/ciclos/$dataInicio',
  path: '/ciclos/$dataInicio',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasNomePessoaRendimentosNomeRoute =
  PessoasNomePessoaRendimentosNomeRouteImport.update({
    id: '/pessoas/$nomePessoa/rendimentos/$nome',
    path: '/pessoas/$nomePessoa/rendimentos/$nome',
    getParentRoute: () => rootRouteImport,
  } as any)
const PessoasNomeRendimentosAdicionarNoCicloAtualRoute =
  PessoasNomeRendimentosAdicionarNoCicloAtualRouteImport.update({
    id: '/pessoas/$nome/rendimentos/adicionarNoCicloAtual',
    path: '/pessoas/$nome/rendimentos/adicionarNoCicloAtual',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ciclos/$dataInicio': typeof CiclosDataInicioRoute
  '/pessoas/adicionarNoCicloAtual': typeof PessoasAdicionarNoCicloAtualRoute
  '/pessoas/$nome/rendimentos/adicionarNoCicloAtual': typeof PessoasNomeRendimentosAdicionarNoCicloAtualRoute
  '/pessoas/$nomePessoa/rendimentos/$nome': typeof PessoasNomePessoaRendimentosNomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ciclos/$dataInicio': typeof CiclosDataInicioRoute
  '/pessoas/adicionarNoCicloAtual': typeof PessoasAdicionarNoCicloAtualRoute
  '/pessoas/$nome/rendimentos/adicionarNoCicloAtual': typeof PessoasNomeRendimentosAdicionarNoCicloAtualRoute
  '/pessoas/$nomePessoa/rendimentos/$nome': typeof PessoasNomePessoaRendimentosNomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ciclos/$dataInicio': typeof CiclosDataInicioRoute
  '/pessoas/adicionarNoCicloAtual': typeof PessoasAdicionarNoCicloAtualRoute
  '/pessoas/$nome/rendimentos/adicionarNoCicloAtual': typeof PessoasNomeRendimentosAdicionarNoCicloAtualRoute
  '/pessoas/$nomePessoa/rendimentos/$nome': typeof PessoasNomePessoaRendimentosNomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ciclos/$dataInicio'
    | '/pessoas/adicionarNoCicloAtual'
    | '/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
    | '/pessoas/$nomePessoa/rendimentos/$nome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ciclos/$dataInicio'
    | '/pessoas/adicionarNoCicloAtual'
    | '/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
    | '/pessoas/$nomePessoa/rendimentos/$nome'
  id:
    | '__root__'
    | '/'
    | '/ciclos/$dataInicio'
    | '/pessoas/adicionarNoCicloAtual'
    | '/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
    | '/pessoas/$nomePessoa/rendimentos/$nome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CiclosDataInicioRoute: typeof CiclosDataInicioRoute
  PessoasAdicionarNoCicloAtualRoute: typeof PessoasAdicionarNoCicloAtualRoute
  PessoasNomeRendimentosAdicionarNoCicloAtualRoute: typeof PessoasNomeRendimentosAdicionarNoCicloAtualRoute
  PessoasNomePessoaRendimentosNomeRoute: typeof PessoasNomePessoaRendimentosNomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas/adicionarNoCicloAtual': {
      id: '/pessoas/adicionarNoCicloAtual'
      path: '/pessoas/adicionarNoCicloAtual'
      fullPath: '/pessoas/adicionarNoCicloAtual'
      preLoaderRoute: typeof PessoasAdicionarNoCicloAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciclos/$dataInicio': {
      id: '/ciclos/$dataInicio'
      path: '/ciclos/$dataInicio'
      fullPath: '/ciclos/$dataInicio'
      preLoaderRoute: typeof CiclosDataInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas/$nomePessoa/rendimentos/$nome': {
      id: '/pessoas/$nomePessoa/rendimentos/$nome'
      path: '/pessoas/$nomePessoa/rendimentos/$nome'
      fullPath: '/pessoas/$nomePessoa/rendimentos/$nome'
      preLoaderRoute: typeof PessoasNomePessoaRendimentosNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas/$nome/rendimentos/adicionarNoCicloAtual': {
      id: '/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
      path: '/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
      fullPath: '/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
      preLoaderRoute: typeof PessoasNomeRendimentosAdicionarNoCicloAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CiclosDataInicioRoute: CiclosDataInicioRoute,
  PessoasAdicionarNoCicloAtualRoute: PessoasAdicionarNoCicloAtualRoute,
  PessoasNomeRendimentosAdicionarNoCicloAtualRoute:
    PessoasNomeRendimentosAdicionarNoCicloAtualRoute,
  PessoasNomePessoaRendimentosNomeRoute: PessoasNomePessoaRendimentosNomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
