/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpostosCasaIndexRouteImport } from './routes/ImpostosCasa/index'
import { Route as ImpostosCasaPessoasAdicionarNoCicloAtualRouteImport } from './routes/ImpostosCasa/pessoas.adicionarNoCicloAtual'
import { Route as ImpostosCasaCiclosDataInicioRouteImport } from './routes/ImpostosCasa/ciclos.$dataInicio'
import { Route as ImpostosCasaPessoasNomePessoaRendimentosNomeRouteImport } from './routes/ImpostosCasa/pessoas.$nomePessoa.rendimentos.$nome'
import { Route as ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRouteImport } from './routes/ImpostosCasa/pessoas.$nomePessoa.gastos.adicionarNoCicloAtual'
import { Route as ImpostosCasaPessoasNomePessoaGastosNomeRouteImport } from './routes/ImpostosCasa/pessoas.$nomePessoa.gastos.$nome'
import { Route as ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRouteImport } from './routes/ImpostosCasa/pessoas.$nome.rendimentos.adicionarNoCicloAtual'

const ImpostosCasaIndexRoute = ImpostosCasaIndexRouteImport.update({
  id: '/ImpostosCasa/',
  path: '/ImpostosCasa/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostosCasaPessoasAdicionarNoCicloAtualRoute =
  ImpostosCasaPessoasAdicionarNoCicloAtualRouteImport.update({
    id: '/ImpostosCasa/pessoas/adicionarNoCicloAtual',
    path: '/ImpostosCasa/pessoas/adicionarNoCicloAtual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImpostosCasaCiclosDataInicioRoute =
  ImpostosCasaCiclosDataInicioRouteImport.update({
    id: '/ImpostosCasa/ciclos/$dataInicio',
    path: '/ImpostosCasa/ciclos/$dataInicio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImpostosCasaPessoasNomePessoaRendimentosNomeRoute =
  ImpostosCasaPessoasNomePessoaRendimentosNomeRouteImport.update({
    id: '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome',
    path: '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRoute =
  ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRouteImport.update({
    id: '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual',
    path: '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImpostosCasaPessoasNomePessoaGastosNomeRoute =
  ImpostosCasaPessoasNomePessoaGastosNomeRouteImport.update({
    id: '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome',
    path: '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRoute =
  ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRouteImport.update({
    id: '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual',
    path: '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/ImpostosCasa': typeof ImpostosCasaIndexRoute
  '/ImpostosCasa/ciclos/$dataInicio': typeof ImpostosCasaCiclosDataInicioRoute
  '/ImpostosCasa/pessoas/adicionarNoCicloAtual': typeof ImpostosCasaPessoasAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual': typeof ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome': typeof ImpostosCasaPessoasNomePessoaGastosNomeRoute
  '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual': typeof ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome': typeof ImpostosCasaPessoasNomePessoaRendimentosNomeRoute
}
export interface FileRoutesByTo {
  '/ImpostosCasa': typeof ImpostosCasaIndexRoute
  '/ImpostosCasa/ciclos/$dataInicio': typeof ImpostosCasaCiclosDataInicioRoute
  '/ImpostosCasa/pessoas/adicionarNoCicloAtual': typeof ImpostosCasaPessoasAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual': typeof ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome': typeof ImpostosCasaPessoasNomePessoaGastosNomeRoute
  '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual': typeof ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome': typeof ImpostosCasaPessoasNomePessoaRendimentosNomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ImpostosCasa/': typeof ImpostosCasaIndexRoute
  '/ImpostosCasa/ciclos/$dataInicio': typeof ImpostosCasaCiclosDataInicioRoute
  '/ImpostosCasa/pessoas/adicionarNoCicloAtual': typeof ImpostosCasaPessoasAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual': typeof ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome': typeof ImpostosCasaPessoasNomePessoaGastosNomeRoute
  '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual': typeof ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRoute
  '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome': typeof ImpostosCasaPessoasNomePessoaRendimentosNomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ImpostosCasa'
    | '/ImpostosCasa/ciclos/$dataInicio'
    | '/ImpostosCasa/pessoas/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome'
    | '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ImpostosCasa'
    | '/ImpostosCasa/ciclos/$dataInicio'
    | '/ImpostosCasa/pessoas/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome'
    | '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome'
  id:
    | '__root__'
    | '/ImpostosCasa/'
    | '/ImpostosCasa/ciclos/$dataInicio'
    | '/ImpostosCasa/pessoas/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome'
    | '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual'
    | '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ImpostosCasaIndexRoute: typeof ImpostosCasaIndexRoute
  ImpostosCasaCiclosDataInicioRoute: typeof ImpostosCasaCiclosDataInicioRoute
  ImpostosCasaPessoasAdicionarNoCicloAtualRoute: typeof ImpostosCasaPessoasAdicionarNoCicloAtualRoute
  ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRoute: typeof ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRoute
  ImpostosCasaPessoasNomePessoaGastosNomeRoute: typeof ImpostosCasaPessoasNomePessoaGastosNomeRoute
  ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRoute: typeof ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRoute
  ImpostosCasaPessoasNomePessoaRendimentosNomeRoute: typeof ImpostosCasaPessoasNomePessoaRendimentosNomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ImpostosCasa/': {
      id: '/ImpostosCasa/'
      path: '/ImpostosCasa'
      fullPath: '/ImpostosCasa'
      preLoaderRoute: typeof ImpostosCasaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ImpostosCasa/pessoas/adicionarNoCicloAtual': {
      id: '/ImpostosCasa/pessoas/adicionarNoCicloAtual'
      path: '/ImpostosCasa/pessoas/adicionarNoCicloAtual'
      fullPath: '/ImpostosCasa/pessoas/adicionarNoCicloAtual'
      preLoaderRoute: typeof ImpostosCasaPessoasAdicionarNoCicloAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ImpostosCasa/ciclos/$dataInicio': {
      id: '/ImpostosCasa/ciclos/$dataInicio'
      path: '/ImpostosCasa/ciclos/$dataInicio'
      fullPath: '/ImpostosCasa/ciclos/$dataInicio'
      preLoaderRoute: typeof ImpostosCasaCiclosDataInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome': {
      id: '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome'
      path: '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome'
      fullPath: '/ImpostosCasa/pessoas/$nomePessoa/rendimentos/$nome'
      preLoaderRoute: typeof ImpostosCasaPessoasNomePessoaRendimentosNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual': {
      id: '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual'
      path: '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual'
      fullPath: '/ImpostosCasa/pessoas/$nomePessoa/gastos/adicionarNoCicloAtual'
      preLoaderRoute: typeof ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome': {
      id: '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome'
      path: '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome'
      fullPath: '/ImpostosCasa/pessoas/$nomePessoa/gastos/$nome'
      preLoaderRoute: typeof ImpostosCasaPessoasNomePessoaGastosNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual': {
      id: '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
      path: '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
      fullPath: '/ImpostosCasa/pessoas/$nome/rendimentos/adicionarNoCicloAtual'
      preLoaderRoute: typeof ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ImpostosCasaIndexRoute: ImpostosCasaIndexRoute,
  ImpostosCasaCiclosDataInicioRoute: ImpostosCasaCiclosDataInicioRoute,
  ImpostosCasaPessoasAdicionarNoCicloAtualRoute:
    ImpostosCasaPessoasAdicionarNoCicloAtualRoute,
  ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRoute:
    ImpostosCasaPessoasNomeRendimentosAdicionarNoCicloAtualRoute,
  ImpostosCasaPessoasNomePessoaGastosNomeRoute:
    ImpostosCasaPessoasNomePessoaGastosNomeRoute,
  ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRoute:
    ImpostosCasaPessoasNomePessoaGastosAdicionarNoCicloAtualRoute,
  ImpostosCasaPessoasNomePessoaRendimentosNomeRoute:
    ImpostosCasaPessoasNomePessoaRendimentosNomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
